### ISSUE TITLE
MP Config: Add in Related Guides link to the static MP Config guide

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-microprofile-config#146]
When we hear that the static MP Config guide is published, add in the link to that guide from our interactive guide.

To do:  In microprofile-config-guide.html add the following line:

related-guides: ['microprofile-config']

after the 'duration: 25 minutes' line.

**Comment by steven1046** [comment]
This might not be a related guide, it depends on the content of each guide.
