### ISSUE TITLE
File names in editor grow indefinitely

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/iguide-microprofile-config#150]
The names of files in editor grow and shrink based on the browser window size (viewport).  The problem is that they do not stop growing, so on an ultrawide monitor it renders like the below:
![image](https://user-images.githubusercontent.com/3076261/35019486-cadda1b2-faec-11e7-8a9c-3b570c0af5cb.png)
![image](https://user-images.githubusercontent.com/3076261/35019493-d450233c-faec-11e7-83f3-41216af32bc0.png)

We need to stop growing once we've reached max width of the website (I'm guessing 1200px) and it no longer re-flows, or do something else entirely regarding the text size of the file names.

**Comment by dmorgant** [comment]
This was fixed as part of Issue #69.
