### ISSUE TITLE
Environment variables from the command line

### ISSUE THREAD

**Issue by alexmacavei** [OpenLiberty/iguide-microprofile-config#170]
There's a small sentence mentioning that env variables can be passed from the command line. Could I see an example of that? I can't seem to get anything working :( 
My setup: 
- simple dockerized microservice based on open-liberty:microProfile1-java8-ibm
- need an env var that's configurable at runtime
- I have defined this property in the microprofile-config.properties file, but I need to overwrite it when I do "docker run my_image"

https://www.ibm.com/support/knowledgecenter/en/SSAW57_8.5.5/com.ibm.websphere.wlp.nd.doc/ae/twlp_admin_customvars.html mentions also that "You can also specify these environment variables in the shell environment, but the server.env files take precedence over those variables."... sadly, again there isn't an example.

UPDATE:
My somewhat clumsy workaround to this is:
- define ENTRYPOINT in my own Dockerfile, overwriting the one in the microprofile parent image like so: 
```docker
ENTRYPOINT java -DMY_VAR=$MY_VAR -javaagent:/opt/ol/wlp/bin/tools/ws-javaagent.jar -jar /opt/ol/wlp/bin/tools/ws-server.jar defaultServer
```
- run the container with my env var set at runtime:
```
docker run -e MY_VAR=foobar my_image
```

Feels kind of odd to do this though...

**Comment by aguibert** [comment]
hi @alexmacavei normally I just `echo` the file in my build script, like this:

```bash
echo "MY_VAR=$MY_VAR" > /path/to/wlp/usr/servers/myServer/server.env
```

Also, note that `server.env` is for environment variables, and `jvm.options` is for JVM options (both of which can be read by MP Config)

**Comment by NottyCode** [comment]
I've just taken the guide and put it into a docker container and executed the following:

docker run -p 9080:9080 -e io_openliberty_guides_email=my.email@my.domain.com my_image

and when I accessed http://localhost:9080/config I was given back a json that had my email address in place of the default specified in microprofile-config.properties.

I didn't override ENTRYPOINT and I didn't put any echo in place for server.env, it just worked out of the box.
