### ISSUE TITLE
Playground: Keep Interactive cards instead of creating a table

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguide-microprofile-config#172]
- keeping the interactive cards instead of moving to table view
  - possibly resize/restyle to fit the space allocated

**Comment by dmorgant** [comment]
Changes to be made to playground following the 11/14 internal review:
- [ ] Center the diagram and the table in the pod
- [ ] Allow the table to scroll to see additional entries if new property values are added
- [ ] Add the styling of the table seen in single column view to that in multi-column view.
