### ISSUE TITLE
MPConfig multipane: put focus to a widget during transition of instruction

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-microprofile-config#190]
After each instruction is completed, make sure focus is set to the next logical widget.

**Comment by lavenal** [comment]
At this moment, there is no need to mark active widget after the instruction is complete as the browser is always in full height with two widgets. I'll keep this issue in open state until an internal playback approves the current right column design.

**Comment by dmorgant** [comment]
Been approved to keep only 2 widgets in the right column.  Closing.
