### ISSUE TITLE
Review #3

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/iguide-microprofile-config#54]
- [x] Change url to not be localhost, change cars-type to car-types, take out port
- [x] Get rid of the WLP setting in server.env
- [x] System props step ordering is unclear because the 4th one is the highest priority when merging
- [ ] status bar at bottom of browser saying 'connecting to' or 'retrieving data from' server on port 'x'
- [x] add microprofile link in what you'll learn

**Comment by steven1046** [comment]
I'll work on the system props step.

**Comment by erica-banda-03** [comment]
I can work on adding the status bar to the bottom of the browser.
