### ISSUE TITLE
[Step 3] Inject using environment variable

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/iguide-microprofile-config#7]
Use environment variable (default ordinal = 300) to override the config file ordinal. (using liberty config file)

**Comment by lavenal** [comment]
PR #10 for initial drop.
PR #11 to use Run button and change ftp url from "us" to "canada".

**Comment by lavenal** [comment]
Waiting for the tab implementation of the editor in iguides-common to complete the step.

**Comment by lavenal** [comment]
PR #19 to add support of tabbed editor.
PR #28 to add error support for tabbed editor.

I'm closing this issue as the remaining work is scenario related.
