### ISSUE TITLE
Jekyll build break due to regular expression

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguide-microprofile-config#75]
# Problem
I have confirmed that the error below is showing up when building the staging website (openlibertydev.mybluemix.net) with the interactive microprofile config guide.  I was able to recreate this error locally.

# Build Error
```
Configuration file: src/main/content/_config.yml
            Source: src/main/content
       Destination: target/jekyll-webapp
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    SyntaxError: Invalid regular expression: /(?<=\().*(?=\))/: Invalid group
  Liquid Exception: SyntaxError: Invalid regular expression: /(?<=\().*(?=\))/: Invalid group in /_layouts/default.html
jekyll 3.6.2 | Error:  SyntaxError: Invalid regular expression: /(?<=\().*(?=\))/: Invalid group

Finished: FAILED
```

**Comment by steven1046** [comment]
![image](https://user-images.githubusercontent.com/6392944/33667508-a11d0be2-da62-11e7-8361-2e34c2d61840.png)

**Comment by kinueng** [comment]
Commit b2586b9 will fix the build break

**Comment by kinueng** [comment]
Confirmed that the build break is resolved in the toolchain.
