### ISSUE TITLE
Console errors on playground 

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguide-microprofile-config#80]
# Steps
- Go to https://openlibertydev.mybluemix.net/guides/microprofile-config-intro.html#default-configsources-playground
- Observe first error in console tab
![image](https://user-images.githubusercontent.com/31117513/33726683-57e78acc-db3b-11e7-902d-f0de3075b6bf.png)
- Click `Run` button
- Observe second error in console tab
![image](https://user-images.githubusercontent.com/31117513/33726709-64124724-db3b-11e7-810d-fa346ff56840.png)

**Comment by kinueng** [comment]
The problem is most likely due to the website pulling the wrong branches.   I will change the `git clone` command to pull the `dev` branch of both `iguides-common` and `iguide-microprofile-config`

**Comment by kevinwlau** [comment]
This is caused by the addition of error message support in the tabbedEditor of `iguide-microprofile-config`, which is reliant on a new commit in `iguides-common` `dev` branch.

**Comment by kinueng** [comment]
I am going to leave the original script to build with master branches.  I will use kinueng/openliberty.io fork to build the dev branches for commons and iguide

**Comment by kinueng** [comment]
I will force qa-guides to always build with `dev` branch of `iguides-common`

Everything working now
https://qa-guides.mybluemix.net/guides/microprofile-config-intro.html#default-configsources-playground
