### ISSUE TITLE
Fix timing issue in playground

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/iguide-microprofile-config#90]
If you load the guide from default http://localhost:4000/guides/microprofile-config-intro.html in a new tab to not use session storage, it has a bug that looks like the playground callback didn't load properly.

![image](https://user-images.githubusercontent.com/6392944/33782795-a750797c-dc1f-11e7-8f81-dbc51ddf7860.png)

**Comment by kevinwlau** [comment]
I'm not seeing this issue anymore. Is it still reproducible?

**Comment by steven1046** [comment]
Yes it is still a bug. To reproduce remove the retry from:

var __createPlayground = function(root, stepName) {
        // If root is not a jQuery element, get the jQuery element from the root object passed in
        if(!root.selector){
            root = root.contentRootElement;
        }

        var pg = playground.create(root, stepName);
        var populateContents = function() {
            // Wait until all 4 editors have been loaded to call update the properties so the editors have time to load
            setTimeout(function(){
                try {
                    pg.repopulatePlaygroundConfigs();
                } catch (e) {
                    console.log("Unable to prepopulate the config sources. Click run on the editor to retrieve the values. Retrying");
                    populateContents();
                }            
            }, 250);
        }
        populateContents();
        root.playground = pg;

        contentManager.setPlayground(stepName, pg, 0);
    };

**Comment by kinueng** [comment]
Has workaround.  Just need to have a better solution
